### ISSUE TITLE
Error al generar cargo

### ISSUE THREAD

**Issue by Neobugu** [conekta/conekta-php#106]
Mientras realizando cargos de prueba en mi servidor, me arroja este error

`Parse error: syntax error, unexpected T_OBJECT_OPERATOR in C:\xampp\htdocs\lib_knt\Conekta\Resource.php on line 206`

Esto a que se debe? Los archivos fueron descargados directamente de la pagina conekta

**Comment by vicentemendoza** [comment]
Hola @Neobugu , que version de php estas usando?

**Comment by Neobugu** [comment]
En mi servidor de pruebas PHP Version 5.3.1

**Comment by eduardoconekta** [comment]
@Neobugu  que version de nuestra libreria tienes ?

**Comment by Neobugu** [comment]
Donde puedo revisar esa informacion, la lib se descargo aprox hace 7 meses

**Comment by eduardoconekta** [comment]
@Neobugu  `/conekta-php/lib/Conekta/Conekta.php` en esa ruta hay una variable 
```
    const VERSION = '4.0.0';
```

**Comment by Neobugu** [comment]
const VERSION = '3.3.0';

**Comment by eduardoconekta** [comment]
@Neobugu Te comento que revises la compatibilidad de tu version especifica de php de tu servidor de prueba con  el error nos indica T_OBJECT_OPERATOR, posiblemente esa sintaxis no estaba habilitada para 5.3.1
 si gustas descargar nuestra ultima version con soporte para php 5.3  te dejo el enlace https://github.com/conekta/conekta-php/tree/php-v3

**Comment by Neobugu** [comment]
Ya realice la prueba con la version que me comentaste, lamentablemente marca el mismo error.

**Comment by eduardoconekta** [comment]
Ok @Neobugu el error recae en que la version que tienes no acepta 
```
$parent_class = strtolower((new \ReflectionClass($parent))->getShortName());
```
podrias intentar esta sintaxis en resource por favor 
```
protected function _createMemberWithRelation($member, $params, $parent)
  {
    $reference = (new \ReflectionClass($parent));
    $reference = $reference->getShortName();
    $parent_class = strtolower($reference);
    $child = self::_createMember($member, $params);
    $child->$parent_class = $parent;
    
    return $child;
  }```

**Comment by Neobugu** [comment]
Realizando dicho cambio arroja siguiente error:

`Parse error: syntax error, unexpected '[' in C:\xampp\htdocs\lib_knt\Conekta\Exceptions\Handler.php on line 51`

**Comment by eduardoconekta** [comment]
Perdona los inconvenientes, pero hemos tenido algunos cambios que tocaron partes de php 7 y deprecaron la version 5.3 en algunos casos como este, podrias cambiar esa linea 
```
$errorStack = [];
```
por esta ? 
```
$errorStack = array();
```
estamos capturando todos los errores para que podamos sacar una nueva version de la rama php-v3

**Comment by Neobugu** [comment]
Cambio realizado
`Parse error: syntax error, unexpected '[' in C:\xampp\htdocs\lib_knt\Conekta\Exceptions\Handler.php on line 71`

**Comment by eduardoconekta** [comment]
@Neobugu  muchas gracias ahora seria 
```
$errorStack['type'] = ["error_type"=>$type,"error_code" => $httpCode];
```
por esta 
```
$errorStack['type'] = array("error_type"=>$type,"error_code" => $httpCode);
```

**Comment by eduardoconekta** [comment]
En caso de tener mas errores tendría que abrir un issue para hacer el refactor completo de la librería, ya que no es viable debuggear de esta forma, como solucion para ti creo que podrias emparejar la version de tu servidor con la version donde hiciste tus pruebas locales, o esperar a que podamos hacer el refactor que estaria en aprox una semana

**Comment by Neobugu** [comment]
El unico problema de mi servidor de pruebas, es que la funcion de mssql_connect ocasiona ciertos problemas en versiones actuales, por eso se escogio version anterior, donde no de problemas, pero realizare pruebas en mi servidor de produccion.

Gracias

**Comment by Neobugu** [comment]
En mi servidor de produccion ya pude terminar token->orders correctamente, muchas gracias por su apoyo, esperando una actualizacion de la version 3.

**Comment by eduardoconekta** [comment]
Gracias a ti @Neobugu

**Comment by Neobugu** [comment]
@eduardoconekta para dicho issue que comentas para el refactor, como lo debo de hacer?

**Comment by eduardoconekta** [comment]
@Neobugu yo hago el pull request sobre los cambios, es todo por tu parte lo que resta es probar la version 5.3 con php-v3 de nosotros :)
