### ISSUE TITLE
error 500 api error

### ISSUE THREAD

**Issue by Neobugu** [conekta/conekta-php#109]
Al tratar de realizar pruebas con a libreria nueva, me arrojo error con codigo 500, revise mi codigo y no hay nada nuevo ni raro, alguna solucion?

Ya probe version 2 y 3, mismo error. (ya no dan servicio por twitter?)

**Comment by mauroarcet** [comment]
Hola @Neobugu, ¿Puedes mandarnos un correo a soporte@conekta.com?

A esta versión de la librería ya no damos soporte pero con la más nueva con gusto te atendemos,

¡Saludos!

**Comment by Neobugu** [comment]
Ya no dan servicio a la version 4? baia, si les mande correo pero no tuve respuesta.

**Comment by lu1s** [comment]
@Neobugu Si puedes explicar con mucho más detalle cómo reproducir el error, detalles de configuraciones e incluso screenshots, sería más fácil que te pudiéramos ayudar. Saludos.

**Comment by iDavidCode** [comment]
entonces cual versión seria la mas estable ? trato de implementarla pero no he podido.

**Comment by vicentemendoza** [comment]
La version 4.0.4

https://packagist.org/packages/conekta/conekta-php

**Comment by iDavidCode** [comment]
ya tengo la librería de conekta-php v4.0.4 desde su [repo](https://github.com/conekta/conekta-php) 

y me marca error 500 quisiera saber si me pueden orientar espero no estar tan perdido

`<?
header('Access-Control-Allow-Origin: *'); 
//require_once("lib/Conekta.php");
require_once("conekta-php/lib/Conekta.php");
\Conekta\Conekta::setApiKey("XXXXX");
\Conekta\Conekta::setApiVersion("4.0.0");

//$token_id=$_POST['token'];

\Conekta\Order::create(array(
  'currency' => 'MXN',
  'customer_info' => array(
    'customer_id' => 'cus_2j9UeJE73wr4v3rrP'
  ),
  'line_items' => array(
    array(
      'name' => 'Box of Cohiba S1s',
      'unit_price' => 35000,
      'quantity' => 1
    )
  ),
  'charges' => array(
    array(
      'payment_method' => array(
        'type' => 'default'
      )
    )
  )
));

?>
`

**Comment by vicentemendoza** [comment]
Tendras el mensaje que te regresamos?

**Comment by iDavidCode** [comment]
Estoy en eso. dame un momento.

**Comment by mauroarcet** [comment]
Hola @iDavidCode, la versión de la API que hay que uilizar es la 2.0.0. [En tu código](https://gist.github.com/iDavidCode/3ea97c0f3236777c370c4737d42d2e5e#file-conekta-php-L6) tienes  "4.0.0". Te comparto nuestro tutorial para cualquier duda que tengas: https://developers.conekta.com/tutorials/card?language=php.

**Comment by iDavidCode** [comment]
Muchas gracias por sus prontas respuestas! 
Muchas gracias @mauroarcet entiendo me estaría quedando [así](https://gist.github.com/iDavidCode/7ebc0103906f2c5a0aa9ced40c4ada8e) 
 y la librería que me recomiendas para comunicarme con su API v2.0.0 ¿Donde la puedo descargar si no es mucha molestia?

**Comment by vicentemendoza** [comment]
@iDavidCode aqui el problema es que la version de la libreria de php si esta bien la version 4.0.0, la version que se setea en el código es la version 2.0.0 (Esta version es de nuestra api, no de la libreria).

**Comment by iDavidCode** [comment]
Muchas gracias ya vamos por menos!!! ahora me marca "El parametro paid_transactions" es requerido." se que lo tengo que agregar pero no veo bien donde!

**Comment by iDavidCode** [comment]
Cuando uso este [curl](https://gist.github.com/iDavidCode/23299a81ceef16286cc95588973bf13a) en mi terminal funciona correctamente.

Pero cuando intento correr el mismo ejemplo  antes señalado el PHP en mi servidor para comunicarme con su API 2.0.0 con la librería 4.0.0 que descargue desde "git clone https://github.com/conekta/conekta-php" me marca error 500 

Intento acercarlo mas a lo que necesito les dejo el [código](https://gist.github.com/iDavidCode/85849ef8cbe053b9f5190729081d0061) y me sigue marcando el error 500 siento que tiene algo que ver con la sintaxis ¿Alguna idea?

**Comment by iDavidCode** [comment]
Ya quedo. les dejo el código por aquí espero a mas de alguno le ayude.
estuve hablando con leo de conekta.io y me ayudo diciendo que en la plataforma hay un apartado de LOGS HTTP donde nos permite ver las solicitudes que se están mandando. 

[CODIGO](https://gist.github.com/iDavidCode/80d09c4849f3b4bb0f001cf9c00e9d24)
