### ISSUE TITLE
HTTP_RAW_POST_DATA deprecated

### ISSUE THREAD

**Issue by bryanisimo** [conekta/conekta-php#11]
When I use this framework, I got this issue

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

**Comment by MauricioMurga** [comment]
Hola @bryanisimo, al parecer no es un problema de la librería ni de tu código sino un problema con la configuración de tu servidor. Encontré esto en [stackoverflow](http://stackoverflow.com/questions/26261001/warning-about-http-raw-post-data-being-deprecated) por si te es de utilidad.

**Comment by bryanisimo** [comment]
Sí ya lo configuré, pero para futuras versiones de PHP será eliminada esa opción para que lo tomen en cuenta; Gracias.
