### ISSUE TITLE
I was using earlier version of sdk.How to migrate 

### ISSUE THREAD

**Issue by harminder-emobx-com** [conekta/conekta-php#112]
I was using earlier version of your sdk suddenly it stopped working. I am trying to subscribe users to my packages which are not working its giving some strange errors. Please suggest.

**Comment by mauroarcet** [comment]
Hi @harminder-emobx-com, you can send us a mail to soporte@conekta.com and we'll look into it.

**Comment by danieluyo** [comment]
See #113
