### ISSUE TITLE
get_class passing null is no longer allowed as of PHP 7.2.x

### ISSUE THREAD

**Issue by omar10594** [conekta/conekta-php#113]
En la version 7.2.0 de php ya no es valido pasar `null` a la funcion `get_class`.

Nosotros solo manejamos subscripciones, asi que despues de actualizar la version de php, no se pueden crear subscripciones debido a que la funcion `createSubscription` de `Conekta\Customer` usa `_createMember` de `ConektaResource`, que es donde se usa la funcion `get_class`.

https://github.com/conekta/conekta-php/blob/14001c78c186157bf709cbe14d3b1a1fecfd2656/lib/Conekta/ConektaResource.php#L145-L155

Y si el cliente se creo e inmediatamente se uso para crear una subscripcion, `$this->$member` (`$this->subscription`) es null.

```php
  $customer = \Conekta\Customer::create(/* ... */);
  $customer->createSubscription(/* ... */);
```
```
ErrorException: get_class() expects parameter 1 to be object, null given in /var/www/vendor/conekta/conekta-php/lib/Conekta/ConektaResource.php:151
```

Por lo pronto volvere a php 7.1.
Como dije anteriormente, en nuestra aplicacion solo usamos subscripciones, por lo que puede que pase con otras acciones.

source: http://php.net/manual/en/function.get-class.php

**Comment by alfonsobries** [comment]
+1

**Comment by leofischer** [comment]
Linking to https://github.com/conekta/conekta-php/pull/163

**Comment by leofischer** [comment]
This is now fixed in the most recent conekta-php version https://github.com/conekta/conekta-php/releases/tag/v4.1.0, I hope to update this for php 7.4 in short order
