### ISSUE TITLE
Entorno de pruebas no funciona

### ISSUE THREAD

**Issue by JuanJoseTalancon** [conekta/conekta-php#120]
Al tratar de hacer pruebas en desarrollo no funciona la integración con conekta y arroja el siguiente error.

Uncaught PHP Exception Conekta_ApiError: "There was a runtime error and Conekta engineers have been notified." at ...\vendor\conekta\conekta-php\lib\Conekta\Error.php line 40

**Comment by mauroarcet** [comment]
Hola @JuanJoseTalancon,

Por favor escríbenos a soporte@conekta.com incluyendo el correo con el que incias sesión en Conekta para poder identificar que puede estar pasando,

¡Saludos!
