### ISSUE TITLE
Evitar duplicidad de tarjeta

### ISSUE THREAD

**Issue by Aletz-Arce** [conekta/conekta-php#127]
Hola @eduardoconekta,
Conekta evita de algún modo, agregar mas de una vez, una forma de pago ya sea debito o crédito ?
En el ambiente de sandbox, eso es posible, en producción es el mismo comportamiento ?

Gracias

**Comment by eduardoconekta** [comment]
podrías explicar mas a fondo el caso que comentas  ? @Aletz-Arce 
no se si te refieres a un payment_source, o a la tokenización o quiza tienes un problema en especifico, si pudieras comentarme o compartir código para estar mas en contexto te lo agradeceria 👍

**Comment by Aletz-Arce** [comment]
Hola,
Me refiero a agregar mas de una vez una tarjeta (con los mismo datos) a un cliente.
En sandbox, para la misma tarjeta, siempre regresa el mismo TokenId.
Saludos

**Comment by eduardoconekta** [comment]
si, el mismo comportamiento existe en producción @Aletz-Arce  
lo que podrias hacer es ligar el token a un customer y despues crear la orden con un customer_id por default este customer tendra un payment_source (token_id) asociado siempre el mismo, para eso tendrias que reconocer a tus usuarios cuando inicien sesion o hacer cargos on demand y poner el token_id en el `charge => payment_method => type => card, token_id = $token;`

**Comment by Aletz-Arce** [comment]
Esa aproximación que me comentas de acuerdo a nuestro flujo es la opción menos optima. Ya que implica, estar capturando la tarjeta del lado del cliente en cada venta.

Lo que se intenta, es que el usuario pueda administrar sus formas de pago, desde la edición de su perfil,
esto es registrar/eliminar formas de pago (Que se persisten del lado de conekta).

Para poder hacer esto, espero me puedas validar la siguiente suposición, una forma de verificar la unicidad de la tarjeta es considerando el **Bin**, **Last4** y **Brand**. Es esto correcto ?, si es así, puedo tener la certeza de que la tarjeta ya se registro como una forma de pago previamente ?.

**Comment by eduardoconekta** [comment]
es correcto @Aletz-Arce :)

**Comment by Aletz-Arce** [comment]
Gracias @eduardoconekta,
Agradezco mucho tu retroalimentación.
Igual y se puede agregar la conclusión de este hilo, como un tip en la documentación de Conekta
Saludos
