### ISSUE TITLE
Conflicto entre namespace y require_once

### ISSUE THREAD

**Issue by SergioEnrique** [conekta/conekta-php#13]
Buen día. Estoy tratando de implementar Conekta en un proyecto de Symfony2, pero al querer incluir la librería de PHP de Conekta hay conflicto con los namespaces:

El error: Attempted to load class "Conekta" from namespace "PP\AdventureBundle\Services".
Did you forget a "use" statement for another namespace?
500 Internal Server Error - ClassNotFoundException

El código:
```
<?php
namespace PP\AdventureBundle\Services;
require_once dirname(__FILE__).'/../../../../vendor/conekta/conekta-php/lib/Conekta.php';

class ConektaService
{
	protected $em;

	function __construct($em)
	{
		$this->em = $em;
	}

	public function prueba()
	{
		Conekta::setApiKey('1tv5yJp3xnVZ7eK67m4h');
		return 'hello';
	}
}
```

Me gustaría saber si hay forma de solucionarlo y también sugiero que utilicen namespaces en la librería PHP de Conekta, pues haría todo mucho más fácil y actualizado al desarrollo actual sobre PHP.

Saludos,

Sergio

**Comment by Lomejook** [comment]
Trata de llamar la clase Conekta asi:

\Conekta::setApiKey('1tv5yJp3xnVZ7eK67m4h');

**Comment by MauricioMurga** [comment]
Puedes usar la rama que soporta namespaces https://github.com/conekta/conekta-php/tree/namespaces.

**Comment by SergioEnrique** [comment]
Ya no funciona el link, todavía está disponible el sporte con namespaces?

**Comment by Kentverger** [comment]
Hola @SergioEnrique  utliza la ultima version de la libreria ya incluye los namespaces.

El link ya no esta por que esa rama se mezclo hace algun tiempo.

**Comment by SergioEnrique** [comment]
ok mil gracias!
