### ISSUE TITLE
Publicar el conector en Package (Composer)

### ISSUE THREAD

**Issue by Koronos** [conekta/conekta-php#130]
Es necesario que comiencen a publicar las librerías oficiales en los repositorios de cada lenguaje, uno no puede estar clonando directamente en proyectos propios código que debería ir en el vendor (en el caso de php), lo comento por que tampoco esta publicada la solución de .Net en NuGet... Si no, de menos actualicen la documentación de instalación para que se muestre la forma de instalar el paquete coneckta-php desde github con el composer.

Yo registre el repositorio en el composer.json:

``` json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/conekta/conekta-php"
        }
    ],
}
```

Y se agrega a los paquetes:

``` 
"require":{
     //Other packages...
      "conekta/conekta-php": "^4.0.2"
}

```

Despues de eso solo fue necesario darle:

> composer update

Ya que tengo composer registrado de manera global. Considero que es mucho mas limpio que clonar la librería en tu proyecto.

**Comment by eduardoconekta** [comment]
Tal vez podríamos agregar al README un install via composer @Koronos  por que en efecto si mantenemos el repo en packagist

**Comment by Koronos** [comment]
Que extraño, realice la búsqueda del paquete y no me apareció, por lo mismo lo instale de esa forma, ya removí el repositorio y funciono sin problema, muchas gracias.
