### ISSUE TITLE
Como saber si un "payment source" es debito o credito?

### ISSUE THREAD

**Issue by dedupely** [conekta/conekta-php#132]
Viendo aquí https://developers.conekta.com/api#payment-source dice "card" pero no dice si es debito o credito. En el admin de Conekta sí dice en ordenes. Hay una forma de ver esto en el API?

**Comment by mauroarcet** [comment]
Hola @dedupely por favor mandanos un mail a soporte@conekta.com para que podamos brindarte una solución :)

**Comment by dedupely** [comment]
Gracias! Ya lo mandé.
