### ISSUE TITLE
Suban el tokenizador a NPM

### ISSUE THREAD

**Issue by javorosas** [conekta/conekta-php#136]
Querido Conekta, bienvenidos a 2018, el año en que dominan frameworks como ReactJS y VueJS, en que Webpack nos transpila-minimiza-junta-organiza todo; y en el que usamos NPM para manejar nuestras dependencias del front-end, porque esas 3 herramientas se llevan muy bien juntas.

Por favor suban su tokenizador a NPM.

PS: No encontré un repo del tokenizador, por eso posteo esto aquí.

**Comment by eduenriquez** [comment]
Hola @javorosas gracias por el feedback ya nos han estado comentando acerca de subir el codigo de conekta.js a npm, hace tiempo subimos el codigo a https://www.npmjs.com/package/conekta-card-tokenizer pero tal cual tomamos la libreria e hicimos el package no se si esto les funciona, me podrías confirmar ?

PS: No consideras que quien debería hacer la tokenizacion debería un servicio en el backend ya que al tener conekta.js en tu app expones tu `public_key` a todos tus usuarios que usen tu aplicación ?

**Comment by fruizg0302** [comment]
Voy a cerrar ese issue porque no es relativo directamente a la biblitoeca de PHP.
Saludos.

**Comment by javorosas** [comment]
@eduenriquez Disculpa la respuesta tardía.

Gracias por el link al tokenizador. Sería de mucha ayuda que lo pusieran en [la documentación](https://developers.conekta.com/libraries/javascript), porque hasta ahora no sabía dónde buscarlo.

En respuesta a tu PS: No. El tokenizador siempre se ejecuta en el cliente. Ese es el punto de su existencia, no? Que los datos de pago nunca pasen por nuestro backend, y en su lugar que ustedes se encarguen de procesarlos de manera segura.

Y debería de ser seguro exponer la `public_key`, después de todo es pública y sólo debería de tener permisos de tokenizar tarjetas.

Por favor hazme saber si no estoy entendiendo algo.

Gracias.
