### ISSUE TITLE
"Amount" no es mayor a 0

### ISSUE THREAD

**Issue by javierpr0** [conekta/conekta-php#144]
Estoy implementando Conekta v4.0.1 con Codeigniter y me surge ese error al momento de realizar la orden y no entiendo porque si el monto si es mayor a 0.

La estructura de la petición es la siguiente:

```
try {
        $order = Conekta\Order::create(array(
            'charges' => array(
                'amount' => 1500,
                'payment_method' => array(
                    'token_id' => $card['token_id'],
                    'type' => 'card'
                )
            ),
            'currency' => 'MXN',
            'details' => array(
                'name' => $card['name'],
                'address' => $card['address']['street1'],
                'address2' => $card['address']['street2'],
                'state' => $card['address']['state'],
                'country' => $card['address']['country'],
                'email' => 'test@test.com',
                'phone' => '3333333333'
            ),
            'line_items'=> array(
                'quantity' => 1,
                'name' => 'test',
                'description' => 'Imported from México',
                'unit_price' => 400,
                'type' => 'physical',
            )
        ));
    } catch (Conekta\ProcessingError $error) {
        echo $error->getMessage();
    } catch (Conekta\ParameterValidationError $error) {
        echo $error->getMessage();
    } catch (Conekta\Handler $error) {
        echo $error->getMessage();
    }
```

Error:

> "amount" no es mayor a 0.

**Comment by eduenriquez** [comment]
Hola @javierpr0 el monto que maneja conekta es en `centésimas` entonces cada monto que ingreses sera dividido entre `10000` entonces ya que `1500 / 10000 = 0.15` es por eso que tienes ese error de vuelta. 
todos los montos deben multiplicarse por 10000

**Comment by javierpr0** [comment]
Hola @eduenriquez acabo de realizar la modificación que me comentas y aun así me sigue regresando el mismo error.

> "amount" no es mayor a 0.

y remplace el amount por 2000000 para prueba y el unit_price pero me dio lo mismo.

**Comment by eduenriquez** [comment]
@javierpr0  no solo en `unit_price` se debe hacer el cambio si no en todos los atributos que hagan referencia al total final que es el `amount` de la order 

https://developers.conekta.com/api?language=php#order

aqui puedes encontrar que amount es calculado en base a 
```
amount
integer
Cantidad que se calcula por el sistema a partir de line_items, shipipng_lines, tax_lines y discount_lines.
```
en dichos objetos( line_items, shipipng_lines, tax_lines y discount_lines) debes verificar que se este poniendo el monto correctamente

**Comment by eduenriquez** [comment]
si necesitas ver algún ejemplo puedes hacerlo en los tests de php 

https://github.com/conekta/conekta-php/blob/master/test/Conekta-2.0/OrderTest.php

**Comment by javierpr0** [comment]
@eduenriquez entiendo el punto, aun así algunos de los campos son opcionales, por ejemplo en el de este issue tengo el parametro **ammount** y el **unite_price** que me dices que en todos esos se basa para poder sacar el monto.

Verifique los ejemplos que me enviaste y realice una peticion lo mas igual posible:

```
$orden = ConektaOrder::create(array(
	'currency' => 'MXN',
	'customer_info' => array(
		'name' => $card['name'],
		'email' => 'test@test.com',
		'phone' => '3333333333'
	) ,
	'line_items' => array(
		'name' => 'Taco',
		'description' => 'Taco de Asada',
		'unit_price' => 20000,
		'quantity' => 1
	) ,
	'charges' => array(
		'livemode' => false,
		'payment_method' => array(
			'type' => 'card',
			'token_id' => 'tok_test_visa_4242'
		)
	)
));
```
y lo único que obtengo usando los catch para el mensaje es:
![imagen](https://user-images.githubusercontent.com/10334283/50527567-ce1b6580-0aae-11e9-949a-9b3ec1249e56.png)

y sin usar los catch:
![imagen](https://user-images.githubusercontent.com/10334283/50527604-fefb9a80-0aae-11e9-9cfa-93df7614f107.png)

**Comment by eduenriquez** [comment]
tu objeto charges deberia ser de esta forma 

```
'charges' => array(
		'livemode' => false,
		'payment_method' => array(
			'type' => 'card',
			'token_id' => 'tok_test_visa_4242'
		)
                'amount' => 20000
 	    )
```
charges es el ente que concreta la compra debe ir el monto total de la orden y se valida de igual forma como en la orden.
los dos montos totales tienen distintos comportamientos en orden se hacen diferentes validaciones y en charges se toman las validaciones anteriores y es con este monto que se hace el cargo al tarjeta habiente

**Comment by eduenriquez** [comment]
Tambien te recomiendo implementar la siguiente forma de obtener los errores 

https://developers.conekta.com/api?language=php#errors
```
 catch (\Conekta\Handler $error) {
  //Conekta object props
  $conektaError = $error->getConektaMessage();
  var_dump($conektaError->type);
  var_dump($conektaError->details);
     .
     .
     .
  //Object iteration
  $conektaError = $error->getConektaMessage();
  foreach ($conektaError->details as $key) {
    echo($key->debug_message);
  }
}
```
de esta forma podras saber todos los errores que te regresa el API y no uno por uno ademas de saber el atributo especifico donde tienes el error

**Comment by javierpr0** [comment]
Sinceramente no se porque razón me sigue arrojando el error, ya realice los cambios que me mencionas, del amount, cambiar el objeto charges y aun así me sigue diciendo lo mismo.

Así quedo al final pero no se soluciono:
![imagen](https://user-images.githubusercontent.com/10334283/50527885-d8d6fa00-0ab0-11e9-9c95-37d5e7952b9f.png)

Mismo error:
![imagen](https://user-images.githubusercontent.com/10334283/50527930-13d92d80-0ab1-11e9-8c08-9f7762d0d435.png)

Que podrá ser, por mas parámetros que eh cambiado, la estructura y todo me sigue ocasionando el mismo problema. La librería esta bien importada, el token del front-end funciona bien, aunque aquí pase a usar un token de pruebas, pero aun así sigue en el mismo problema.

**Comment by eduenriquez** [comment]
@javierpr0 
puedes intentar con este snippet hice la prueba y funciona
```
Conekta\Conekta::setApiKey('key_ZLy4aP2szht1HqzkCezDEA');
$order = array(
    'line_items'=> array(
      array(
        'name'=> 'Box of Cohiba S1s',
        'description'=> 'Imported From Mex.',
        'unit_price'=> 20000,
        'quantity'=> 1,
        'sku'=> 'cohb_s1',
        'category'=> 'food',
        'tags' => array('food', 'mexican food')
        )
      ),
    'currency'    => 'mxn',
    'metadata'    => array('test' => 'extra info')
    );
$customerParams = array(
    'currency'    => 'mxn',
    'customer_info' => array(
      'name' => 'John Constantine',
      'phone' => '+5213353319758',
      'email' => 'hola@hola.com'
      )
    );

$validVisaCard =array(
  'payment_method' => array(
    'type' => 'card',
    'token_id' => 'tok_test_visa_4242'
  )
);  
$orderParams = array_merge(self::$order, self::$customerParams);
$order = Conekta\Order::create($orderParams);
$order->createCharge($validVisaCard);    

```

**Comment by javierpr0** [comment]
@eduenriquez imprimi todo los errores y me arroja esto:
```
"amount" no es mayor a 0.

conekta.errors.parameter_validation.amount.number_is_not_greater_than

82

#0 C:\xampp\htdocs\reconekta\application\libraries\conekta\Conekta\Exceptions\Handler.php(96): Conekta\Handler::build(Array, 422) #1 C:\xampp\htdocs\reconekta\application\libraries\conekta\Conekta\Requestor.php(152): Conekta\Handler::errorHandler(Array, 422) #2 C:\xampp\htdocs\reconekta\application\libraries\conekta\Conekta\ConektaResource.php(80): Conekta\Requestor->request('post', 'https://api.con...', Array) #3 C:\xampp\htdocs\reconekta\application\libraries\conekta\Conekta\Order.php(73): Conekta\ConektaResource::_scpCreate('Conekta\\Order', Array) #4 C:\xampp\htdocs\reconekta\application\controllers\Pago.php(37): Conekta\Order::create(Array) #5 C:\xampp\htdocs\reconekta\system\core\CodeIgniter.php(532): Pago->crear() #6 C:\xampp\htdocs\reconekta\index.php(315): require_once('C:\\xampp\\htdocs...') #7 {main}

object(stdClass)#21 (2) { ["details"]=> array(3) { [0]=> object(stdClass)#17 (4) { ["debug_message"]=> string(66) "Invalid datatype for "line_items" expecting at least normal Array." ["message"]=> string(37) ""line_items" tiene un tipo inválido." ["param"]=> string(10) "line_items" ["code"]=> string(63) "conekta.errors.parameter_validation.line_items.invalid_datatype" } [1]=> object(stdClass)#19 (4) { ["debug_message"]=> string(63) "Invalid datatype for "charges" expecting at least normal Array." ["message"]=> string(34) ""charges" tiene un tipo inválido." ["param"]=> string(7) "charges" ["code"]=> string(60) "conekta.errors.parameter_validation.charges.invalid_datatype" } [2]=> object(stdClass)#20 (4) { ["debug_message"]=> string(31) ""amount" is not greater than 0." ["message"]=> string(25) ""amount" no es mayor a 0." ["param"]=> string(6) "amount" ["code"]=> string(69) "conekta.errors.parameter_validation.amount.number_is_not_greater_than" } } ["type"]=> object(stdClass)#22 (2) { ["error_type"]=> string(26) "parameter_validation_error" ["error_code"]=> int(422) } } 

object(stdClass)#17 (2) { ["error_type"]=> string(26) "parameter_validation_error" ["error_code"]=> int(422) } 

array(3) { [0]=> object(stdClass)#21 (4) { ["debug_message"]=> string(66) "Invalid datatype for "line_items" expecting at least normal Array." ["message"]=> string(37) ""line_items" tiene un tipo inválido." ["param"]=> string(10) "line_items" ["code"]=> string(63) "conekta.errors.parameter_validation.line_items.invalid_datatype" } [1]=> object(stdClass)#22 (4) { ["debug_message"]=> string(63) "Invalid datatype for "charges" expecting at least normal Array." ["message"]=> string(34) ""charges" tiene un tipo inválido." ["param"]=> string(7) "charges" ["code"]=> string(60) "conekta.errors.parameter_validation.charges.invalid_datatype" } [2]=> object(stdClass)#20 (4) { ["debug_message"]=> string(31) ""amount" is not greater than 0." ["message"]=> string(25) ""amount" no es mayor a 0." ["param"]=> string(6) "amount" ["code"]=> string(69) "conekta.errors.parameter_validation.amount.number_is_not_greater_than" } } 

Invalid datatype for "line_items" expecting at least normal Array.Invalid datatype for "charges" expecting at least normal Array."amount" is not greater than 0.
```
Al parecer todo lo relacionado con el monto, la ultima linea se ve un poco mas especifica respecto.

El **snippet** que tu me pasaste me arroja lo siguiente:

`El parametro "shipping_lines" es requerido.conekta.errors.precondition_required.shipping_lines.missing86#0 C:\xampp\htdocs\reconekta\application\libraries\conekta\Conekta\Exceptions\Handler.php(96): Conekta\Handler::build(Array, 428) #1 C:\xampp\htdocs\reconekta\application\libraries\conekta\Conekta\Requestor.php(152): Conekta\Handler::errorHandler(Array, 428) #2 C:\xampp\htdocs\reconekta\application\libraries\conekta\Conekta\ConektaResource.php(149): Conekta\Requestor->request('post', 'https://api.con...', Array) #3 C:\xampp\htdocs\reconekta\application\libraries\conekta\Conekta\Order.php(115): Conekta\ConektaResource->_createMember('charges', Array) #4 C:\xampp\htdocs\reconekta\application\controllers\Pago.php(66): Conekta\Order->createCharge(Array) #5 C:\xampp\htdocs\reconekta\system\core\CodeIgniter.php(532): Pago->crear() #6 C:\xampp\htdocs\reconekta\index.php(315): require_once('C:\\xampp\\htdocs...') #7 {main}`

Me pide el shipping_lines, pero los productos son digitales.

**Comment by javierpr0** [comment]
@eduenriquez me acabo de dar cuenta de que no es problema del código, si no de la API, mis API´s son de pruebas, utilice la API que tu me pasaste y no me genero ningún error.

**Comment by eduenriquez** [comment]
@javierpr0 dependiendo de las api keys que estes usando 
producción o sandbox tienes ciertas restricciones 
para producción tu compañia necesita tener activados ciertos parametros internos para poder aceptar tarjetas que creo que ese error es por que estan bloqueados los pagos con tarjeta en tu cuenta ya que en sandbox ninguna compañia tiene ese comportamiento al ser para poder hacer pruebas 
y tambien hay dos llaves, no se si estes usando la privada para hacer las peticiones a backend y las publicas para hacer la tokenización

**Comment by javierpr0** [comment]
@eduenriquez mi cuenta unicamente tiene activadas las API's de pruebas, la publica la estoy utilizando en el Front-end y la privada en el Back-end mas no se porque da error la mía.

**Comment by eduenriquez** [comment]
@javiermurillo  puedes pedir apoyo a soporte@conekta.com

**Comment by javierpr0** [comment]
> 
> 
> @javiermurillo puedes pedir apoyo a [soporte@conekta.com](mailto:soporte@conekta.com)

Te agradezco tu tiempo y la amabilidad, buen día.

**Comment by fruizg0302** [comment]
Voy a cerrar el issue ya que es más un tema de integración que relativo a la bilbioteca. Saludos
