### ISSUE TITLE
Changing Address DATA inside shipping_contacts

### ISSUE THREAD

**Issue by choky10** [conekta/conekta-php#145]
Hello, i get the problem i consult with the team of conekta and i dont ger response.

So all my app work payments,  i just continue with problems doing the title..

So i have this code:

`$shippingContact = $customer->shipping_contacts[0];
	    try{
	      $shippingContact->update(array(
	      	 'receiver' => 'nuevosss',
	      	 'phone' => '+522979702000',
	      	 'between_streets' => 'ENTRE CALLES',
	      	 'address' => array(
	      	 			'city' => 'Xalapa',
	      	 	)
	      ));

	      return $customer->shipping_contacts;
	    }catch (\Exception $e) {
	      $this->assertTrue(strpos(get_class($e), 'ParameterValidationError') == true);
	    }`

The problem is i dont ge any change inside the address..
What i doing wrong?

**Comment by JoValo** [comment]
Hi @choky10 !, your error is in: `'city' => 'Xalapa',` 
```
$validCustomer =  array('email' => 'hola@hola.com',
'name' => 'John Constantine',
'shipping_contacts' => array(
  array(
    'receiver' => 'Jack Bauer',
    'phone' => '+5213353319758',
    'email' => 'thomas.logan@xmen.org',
    'address' => array(
      'street1' => '250 Alexis St',
      'city' => 'Red Deer',
      'state' => 'Alberta',
      'country' => 'CA',
      'postal_code' => 'T4N 0B8'
      )
    ),
  array(
    'receiver' => 'John Williams',
    'phone' => '+5213353319758',
    'email' => 'rogue@xmen.org',
    'address' => array(
      'street1' => '250 Alexis St',
      'city' => 'Red Deer',
      'state' => 'Alberta',
      'country' => 'CA',
      'postal_code' => 'T4N 0B8'
      )
    )
  )
);

$customer = Customer::create($validCustomer);
$shippingContact = $customer->shipping_contacts[0];
try {
  $shippingContact->update(array('receiver' => 'nuevosss', 'phone' => '+522979702000', 'between_streets' => 'ENTRE CALLES', 'address' => array('city' => 'Xalapa')));  
  // Code ...
} catch(Exception $e){
  // Error
}
```

**Comment by leofischer** [comment]
This looks to be a syntax error, so I am going to close this issue.
