### ISSUE TITLE
how can i put cents in unit_price 

### ISSUE THREAD

**Issue by vardash0131** [conekta/conekta-php#151]
in the documentation the unit_price parameter says:
![unit_price](https://user-images.githubusercontent.com/20211190/55744989-e3802400-59fb-11e9-8a2a-78047a80cb96.png)
but the parameter expects a integer  when i try to pass float it says 
![error unit_price](https://user-images.githubusercontent.com/20211190/55745151-2e9a3700-59fc-11e9-9c09-bf777906e659.png)

**Comment by vardash0131** [comment]
deberían especificar en la documentación que se expresa con un 0 en ves de un . es bastante confuso

**Comment by HectorRojasB** [comment]
Y sí necesito expresar el valor 12,020? Qué es lo que tengo que hacer?

**Comment by vardash0131** [comment]
1202000
