### ISSUE TITLE
precondition_required_error Al agregar linea de descuento a una orden.

### ISSUE THREAD

**Issue by lherreranetlink** [conekta/conekta-php#153]
Muy buenas tardes. Estoy tratando de agregar un cupón de descuento a una order que hice y obtengo el siguiente resultado:
![Captura de pantalla 2019-06-14 a la(s) 13 45 57](https://user-images.githubusercontent.com/30661966/59531128-c90a7100-8eaa-11e9-8d08-3f7eb69b2475.png)

Mi código es, en realidad simple.

Tengo la orden, creada sin problemas y una vez creada mando llamar al método `createDiscountOrder` . Algo Cómo esto:

![Captura de pantalla 2019-06-14 a la(s) 13 50 36](https://user-images.githubusercontent.com/30661966/59531390-6d8cb300-8eab-11e9-9c1b-e3a1e66a0f5f.png)

Si quito la llamada a la función `createDiscountOrder` funcionar perfectamente. Solo que obviamente no agrega ningún descuento.

**Comment by JoValo** [comment]
Hola @lherreranetlink !
Actualmente puedes agregar un descuento tal y como indica nuestra [documentación](https://developers.conekta.com/api?language=php#create-discount-line).

También podrías agregar antes de crear la orden el `discount_lines`:
```
$validOrder = array(
    'line_items'=> array(
      array(
        'name'=> 'Box of Cohiba S1s',
        'description'=> 'Imported From Mex.',
        'unit_price'=> 20000,
        'quantity'=> 1,
        'sku'=> 'cohb_s1',
        'category'=> 'food',
        'tags' => array('food', 'mexican food')
        )
      ),
    'currency'    => 'mxn',
    'discount_lines' => array(
      array(
        'code' => 'Cupon de descuento',
        'amount' => 10,
        'type' => 'loyalty'
        )
      )
    );

$order = Order::create($validOrder);
$discountLine = $order->discount_lines[0];
echo $discountLine;
```

Otras acciones que puedes hacer es actualizar el monto del descuento o borrarlo.
```
$discountLine->update(array('amount' => 11));
```

```
$discountLine->delete();
```

**Comment by leofischer** [comment]
Este mensaje de error es confuso, estoy armando un PR para aclararlo.  Sucede para 2 motivos:
-Tienes un order que ya está pagado, preautorizado o con un cargo de OXXO/Spei que sigue vigente para pagar
-Este order no fue creado con la versión 2

**Comment by leofischer** [comment]
Hemos actualizado el api para dar un mensaje de error más intuitivo en estos casos, como el anterior no era muy claro.  Si vuelva a ocurrir ya debería de ser más fácil depurar, de momento voy a cerrar este issue.
