### ISSUE TITLE
Alguien sabe cómo cambiar la tarjeta por default desde la programación?

### ISSUE THREAD

**Issue by chaagopa** [conekta/conekta-php#155]
$client = \Conekta\Customer::find($this->customerId);
    
        $client->payment_sources[1]->update(array(
           "name" => "El Molino Index",
           "default" => $true
        )); 

ya que de esta manera no me lo permite.

**Comment by chaagopa** [comment]
$client = \Conekta\Customer::find($this->customerId); 
$client->update(
            array(
              'default_payment_source_id'  => "yourCardSrc"
            ));

**Comment by krathos** [comment]
Pinche conekta, muchas cosas de su documentacion esta mal
Muchas gracias @chaagopa
