### ISSUE TITLE
Formato inválido para name al crear cargo

### ISSUE THREAD

**Issue by titosobabas** [conekta/conekta-php#166]
Hola, intento hacer un cargo pero me sale este error: Formato inválido para name

Parece que el error tiene algo que ver con el nombre, pero hasta donde veo, todo están bien, ¿o debe de estar en otro formato? 

El array que trato de enviar es el siguiente:

![image](https://user-images.githubusercontent.com/18486020/76090558-6057ad00-5f81-11ea-98e4-0ddbcb74cfaa.png)

Gracias

**Comment by silvaGarduno** [comment]
Hola @titosobabas, me podrías pasar el nombre de tu empresa por favor.
