### ISSUE TITLE
Attempt to assign property 'customer' of non-object on dev-php7.2-support

### ISSUE THREAD

**Issue by zaratedev** [conekta/conekta-php#167]
Cuenta Conekta de entorno de pruebas.

Cuando intento crear un método de pago al customer:

```php
/** @var \Conekta\Card $conektaCard */
$conektaCard = $conektaCustomer->createPaymentSource([
    'token_id' => $attributes['token_id'],
    'type' => 'card',
]);
```
Me devuelve el mensaje "**Attempt to assign property 'customer' of non-object**"

Trate de debuguear el error y al parecer proviene cuando se intenta de asignar `$child->$parent_class = $parent;` en la clase `conekta-php/lib/Conekta/ConektaResource.php`.

```php
protected function _createMemberWithRelation($member, $params, $parent)
{
   $parent_class = strtolower((new \ReflectionClass($parent))->getShortName());
   $child = self::_createMember($member, $params);
   $child->$parent_class = $parent;
    
    return $child;
}
```

En el dashboard de Conekta si se crea el **payment source**.

¿Alguien tiene el mismo problema?

Me podrían indicar a que se debe esto.

**Comment by silvaGarduno** [comment]
Hola @zaratedev.
Podrías revisar lo siguiente por favor
https://developers.conekta.com/api?language=php#create-payment-source

saludos

**Comment by zaratedev** [comment]
@silvaGarduno Gracias. 

Este problema se debe a la versión de PHP, tenia una versión superior a 7.2 😄
