### ISSUE TITLE
"conekta.errors.processing.undefined method `credit_commission' for nil:NilClass"

### ISSUE THREAD

**Issue by AllenWalkerHR** [conekta/conekta-php#168]
Trato de crear una orden y siempre me manda ese error.
Entorno de pruebas.

`$valid_order = array(
            "line_items" => array(
              array(
                "name" => "Producto1",
                "unit_price" => $total*100, 
              )//first line_item
            ), //line_items
            "shipping_lines" => array(
              array(
                "amount" => $total,
                 "carrier" => "FEDEX"
              )
            ), //shipping_lines - physical goods only
            "currency" => "MXN",
            "customer_info" => array(
              "customer_id" => $customer->id 
            ), //customer_info
            "shipping_contact" => array(
              "address" => array(
                "street1" => "Guanajuato",
                "postal_code" => "38940",
                "country" => "MX"
              )//address
            ), //shipping_contact - required only for physical goods
            "charges" => array(
                array(
                    "payment_method" => array(
                            "type" => "default"
                    ) 
                ) //first charge
            ) //charges
          );//order`

**Comment by silvaGarduno** [comment]
Hola @AllenWalkerHR 

Podrías por favor cambiar lo que hay dentro de payment_method por lo siguiente:

Type:    "card",
TokenID: "tok_test_visa_4242",

**Comment by AllenWalkerHR** [comment]
hola ya lo solucione fue problema de activacon de key para uso de la api.
