### ISSUE TITLE
Call to undefined function Conekta

### ISSUE THREAD

**Issue by oswaldo89** [conekta/conekta-php#169]
Hola buen día, estoy implementando conekta con laravel, en mi local si funciona bien todo, pero para probar el webhook, subí el código al server ya me marco el siguiente error, cuando intento crear la orden.

**Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function Conekta\curl_init() in file /var/www/nombre_proyecto/backend_api/vendor/conekta/conekta-php/lib/Conekta/Requestor.php on line 110**

Estoy buscando documentación acerca del error pero no encuentro nada.. 
espero me puedan echar la mano..

Un saludo.!

**Comment by silvaGarduno** [comment]
@oswaldo89 
Me podrías compartir tu correo por favor.

**Comment by oswaldo89** [comment]
con gusto @silvaGarduno , oswaldo.gh89@gmail.com
