### ISSUE TITLE
Unhandled exception on Conekta_Resource

### ISSUE THREAD

**Issue by isaac-rga** [conekta/conekta-php#17]
When excecuting `Conekta_Customer::find()` with parameter as null or empty string, the instance of Conekta_Resource at function instanceUrl() could not throw Conekta_Error exception.

From console...

> [Fri Jul 29 21:09:15 2016] PHP Fatal error:  Class 'LANG' not found in /home/peoplecloud/Projects/peopletrack/vendor/conekta/conekta-php/lib/Conekta/Resource.php on line 69

Using Laravel 4.2 this exception is thrown instead...

> exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'LANG' not found' in /home/peoplecloud/Projects/peopletrack/vendor/conekta/conekta-php/lib/Conekta/Resource.php:69 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleShutdown() #1 {main}

**Comment by MauricioMurga** [comment]
Hola @isaac-rga, una disculpa por la tardada respuesta. ¿Tienes la librería actualizada? Intenté replicar con la versión más reciente y no pude.

Quedo al pendiente de tus comentarios.

**Comment by isaac-rga** [comment]
Ya actualizé y ya arroja la exception.

**Comment by MauricioMurga** [comment]
¡Excelente!, muchas gracias por tu seguimiento.
