### ISSUE TITLE
El parametro "shipping_lines" es requerido.

### ISSUE THREAD

**Issue by aGarcia-AD** [conekta/conekta-php#170]
Hola, estoy intentando implementar los pagos usando PHP pero al intentar crear la orden me regresa el error de 'El parametro "shipping_lines" es requerido.'.
El problema es que sí tengo definido ese parámetro en mi array:
```php
$this->order = \Conekta\Order::create([
                    'currency' => 'MXN',
                    'customer_info' => [
                      'customer_id' => $this->customer->id
                    ],
                    'line_items' => [
                      [
                        'name' => 'Test item',
                        'unit_price' => 35000,
                        'quantity' => 1
                      ]
                    ],
                    'shipping_lines' => [
                        "amount" => 3000,
                        "carrier" => "Test",
                    ],
                    'charges' => [
                      [
                        'payment_method' => [
                          'type' => 'default'
                        ]
                      ]
                    ]
                ]);
```

**Comment by silvaGarduno** [comment]
Hola @aGarcia-AD , te envió un ejemplo de los datos que se deben de enviar a API, me dices si te funciona por favor.

$order = \Conekta\Order::create(
      array(
        "line_items" => array(
          array(
            "name" => "Tacos",
            "unit_price" => 100000,
            "description" => "Replica prueba",
            "quantity" => 1
          )
        ), 
        "shipping_lines" => array(
          array(
            "amount" => 0,
             "carrier" => "FEDEX"
          )
        ),
        "currency" => "MXN",
        "customer_info" => array(
          "name" => "Fulanito",
          "email" => "fulanito@test.com",
          "phone" => "8784342422"
        ), 
        "shipping_contact" => array(
          "address" => array(
            "street1" => "Calle 123, int 2",
            "postal_code" => "06100",
            "country" => "MX"
          )
        ),
        "metadata" => array("order_number" => "1234567810"),
        //"pre_authorize" => true,
        "charges" => array(
            array(
                "payment_method" => array(
                    "type" => "default"
                  ) 
            ) 
        ) 
      )
    );

**Comment by aGarcia-AD** [comment]
Al usar este array me regresa "El usuario no tiene un metodo de pago por default valido.".
Parece ser que con esta estructura si está funcionando.
Gracias por la respuesta.

**Comment by silvaGarduno** [comment]
@aGarcia-AD 

Tienes razón, aqui hay dos formas de mandar esta info.

una es usando el customer_id y el type: default.

y la otra es mandando los datos completos sin tener que registrar el customer en API.
$order = \Conekta\Order::create(
      array(
        "line_items" => array(
          array(
            "name" => "Tacos",
            "unit_price" => 100000,
            "description" => "Replica prueba",
            "quantity" => 1
          )
        ), 
        "shipping_lines" => array(
          array(
            "amount" => 0,
             "carrier" => "FEDEX"
          )
        ),
        "currency" => "MXN",
        "customer_info" => array(
          "name" => "Fulanito",
          "email" => "fulanito@test.com",
          "phone" => "8784342422"
        ), 
        "shipping_contact" => array(
          "address" => array(
            "street1" => "Calle 123, int 2",
            "postal_code" => "06100",
            "country" => "MX"
          )
        ),
        "metadata" => array("order_number" => "1234567810"),
        //"pre_authorize" => true,
        "charges" => array(
            array(
                "payment_method" => array(
                    "type" => "card",
                    "token_id" => "tok_test_mastercard_4444"
                  ) 
            ) 
        ) 
      )
    );

De esta forma te debería de funcionar, puedes probar por favor
