### ISSUE TITLE
how to get all orders

### ISSUE THREAD

**Issue by e-hop** [conekta/conekta-php#171]
Is there any way to get all orders ?? It'll be  nice to have. For example
`\Conekta\Order::all()`

**Comment by silvaGarduno** [comment]
Try with:
\Conekta\Order::where();

**Comment by e-hop** [comment]
> Try with:
> \Conekta\Order::where();

Thank you, it works, but it returns a 20 length array 
![image](https://user-images.githubusercontent.com/62304175/78399227-c13ec900-75b1-11ea-9d41-7c589cd4aadb.png)

**Comment by silvaGarduno** [comment]
ok.
For example, the next code is for limit orders
\Conekta\Order::where(array("limit" => 25));

**Comment by silvaGarduno** [comment]
in this url https://github.com/conekta/conekta-php/blob/master/test/Conekta-2.0/ConektaListTest.php
you can see other examples

**Comment by e-hop** [comment]
thank you. I found the solution using yours. I used 
`\Conekta\Order::where(array("limit" => 0 ));`
and it returned the all records.
