### ISSUE TITLE
El parametro "shipping_lines" es requerido.

### ISSUE THREAD

**Issue by StayTrue10** [conekta/conekta-php#178]
en la documentación dice que no es obligatorio, pero me marca ese error, todo es digital.
```
$order = \Conekta\Order::create(
                array(
                    "line_items" => array(
                        array(
                            "name" => $nomPlan,
                            "unit_price" => $precio*100,
                            "quantity" => 1
                        )//first line_item
                    ), //line_items
                    "currency" => "MXN",
                    "customer_info" => array(
                        "name" => $request->input('sNombreCompleto'),
                        "email" => $request->input('email'),
                        "phone" => $request->input('sTelefono')
                    ),
                    "metadata" => array(
                        "idUsuario" => $idUsuario
                    ),
                    "charges" => array(
                        array(
                            "payment_method" => array(
                                "type" => "oxxo_cash"
                            )//payment_method
                        ) //first charge
                    ) //charges
                )//order
            );
```

**Comment by silvaGarduno** [comment]
Hola @StayTrue10 , para poder enviar los datos también hay que incluir tanto shipping_lines como shipping_contact, si lo que vendes es digital lo podrías especificar dentro de los campos de shipping_line.

**Comment by StayTrue10** [comment]
hola @silvaGarduno entonces debo incluirlos si o si en mi array? aunque sea solo servicio??, me podrías indicar como quedan esos arreglos porfa, para incluirlos.

**Comment by silvaGarduno** [comment]
@StayTrue10 podría ser algo como lo siguiente:

"shipping_lines": [
		{
			"amount": "0",
			"tracking_number": "Digital",
			"carrier": "Producto digital",
			"method": "Digital"
		}
	],
	"shipping_contact": {
		"receiver": "",
		"phone": "",
		"address": {
			"street1": "",
			"city": "",
			"state": "",
			"country": "",
			"postal_code": ""
		},

En los datos de shipping_contact podrías colocar tu información

**Comment by StayTrue10** [comment]
gracias! @silvaGarduno entonces para crear una orden es necesario incluir el shipping_line y shipping_contact,  no importa el método de pago? deberían modificar la documentación y que no diga que es opcional.

**Comment by silvaGarduno** [comment]
@StayTrue10, ya investigue y al parecer si hay una forma para no enviar esos datos, si quieres puedes enviar un correo a soporte@conekta.com especificando este problema y ellos lo podrían resolver para modificar los permisos y permitir que envies los datos sin shipping_line y shipping_contact.

**Comment by StayTrue10** [comment]
ya les envié correo explicándoles, según tardan unas 8 horas hábiles. sino pues así, creo que eso no cambia mucho mi función.
