### ISSUE TITLE
HHVM - Undefined property: Conekta_Card::$customer

### ISSUE THREAD

**Issue by gtrevino** [conekta/conekta-php#18]
Al eliminar una tarjeta me sale el error Undefined property: Conekta_Card::$customer utilizando HHVM como interpretador, con Apache no hay ningún problema, la solución fue editar la clase Customer.php en la linea 12:

Antes
12  $v->customer = &$this;

Después
12  $v->customer = $this;

Saludos developers!

**Comment by MauricioMurga** [comment]
Muchas gracias por tu contribución @gtrevino. Ya agregué los cambios. 👍
