### ISSUE TITLE
agrega .0000001 a mi unit price

### ISSUE THREAD

**Issue by Oscar10056** [conekta/conekta-php#182]
hola al pasar un articulo a pago me agrega .0000000000001 o valores de .999999999999 al valor lo que lo hace invalido.

![image](https://user-images.githubusercontent.com/69607120/90073843-91ba6e80-dcbf-11ea-8f82-f449e5f65e95.png)

me pueden ayudar a resolver, o explicarme por que agrega este valor

**Comment by glavrjk** [comment]
Recuerda que el campo unit_price debe ser numérico entero. Utiliza funciones de redondeo y multiplicación antes del envío para transformar a centavos tus precios

**Comment by Oscar10056** [comment]
> Recuerda que el campo unit_price debe ser numérico entero. Utiliza funciones de redondeo y multiplicación antes del envío para transformar a centavos tus precios

Eso realizo, como se ve en el ejemplo, si fuera error de la función que ocupo lo agregaría a todos los artículos, pero solo lo agrega a 1, y todos los paso por la misma función.

**Comment by glavrjk** [comment]
Puedes compartir el código de petición para verificar porque revisando me doy cuenta que tu unit_price, no coincide con tu precio. Uno es floante y el otro es string y según tengo entendido ese atributo "precio" no debería ir ahí sino en los metadata. Aquí te envío un ejemplo de cómo implementé yo la creación de Órdenes es contra un solo artículo

 ```php
'line_items' => array(
                        [
                            'name' => $art->getDescription(),
                            'unit_price' => round(100 * $art->getPrice()),
                            'quantity' => 1* $art->getCant()
                        ]
                    ),
```

**Comment by Oscar10056** [comment]
Claro este es mi codigo

 
foreach ($tmp_arr as $val) {
        $precio = floatval($val['precio']);
        $precio = $precio*100;
        $color = $val['color'];
        $size = $val['size'];
        if ($color != '' && $size != '') {
            $name = $val['producto'].' color '.$color.' tamaño '.$size.' piezas '.$val['piezas'];
        } else {
            if ($size == '' && $color != '') {
                $name = $val['producto'].' color '.$color.' piezas '.$val['piezas'];    
            } else {
                if ($size != '' && $color == '') {
                    $name = $val['producto'].' tamaño '.$size.' piezas '.$val['piezas'];
                } else {
                    if ($size == '' && $color == '') {
                        $name = $val['producto'].' piezas '.$val['piezas'];
                    }
                }
            }
        }
        $cantidad = $val['can'];
        $precio1 = $val['precio1'];
        $tmp_arr1[] = array(
            "name" => $name,
            "unit_price" => $precio,
            "quantity" => $cantidad,
            "precio" => $precio1
        );
    }

-----Original message-----

**Comment by Oscar10056** [comment]
> Puedes compartir el código de petición para verificar porque revisando me doy cuenta que tu unit_price, no coincide con tu precio. Uno es floante y el otro es string y según tengo entendido ese atributo "precio" no debería ir ahí sino en los metadata. Aquí te envío un ejemplo de cómo implementé yo la creación de Órdenes es contra un solo artículo
> 
> ```
> /** @var Articulo $art  */
> 'line_items' => array(
>                        [
>                            'name' => $art->getDescription(),
>                            'unit_price' => round(100 * $art->getPrice()),
>                            'quantity' => (1 * $art->getCant())
>                        ]
>                    ),
> ```

Claro este es mi codigo que estoy utilzando

foreach ($tmp_arr as $val) {
		$precio = floatval($val['precio']);
		$precio = $precio*100;
		$color = $val['color'];
		$size = $val['size'];
		if ($color != '' && $size != '') {
			$name = $val['producto'].' color '.$color.' tamaño '.$size.' piezas '.$val['piezas'];
		} else {
			if ($size == '' && $color != '') {
				$name = $val['producto'].' color '.$color.' piezas '.$val['piezas'];	
			} else {
				if ($size != '' && $color == '') {
					$name = $val['producto'].' tamaño '.$size.' piezas '.$val['piezas'];
				} else {
					if ($size == '' && $color == '') {
						$name = $val['producto'].' piezas '.$val['piezas'];
					}
				}
			}
		}
		$cantidad = $val['can'];
		$precio1 = $val['precio1'];
		$tmp_arr1[] = array(
			"name" => $name,
			"unit_price" => $precio,
			"quantity" => $cantidad,
			"precio" => $precio1
		);
	}

**Comment by glavrjk** [comment]
Fíjate acá creo que está tu problema, 
```php
$precio = floatval($val['precio']);
$precio = $precio*100;
```
Primeramente, transformas tu variable a flotante. Eso esta bien y luego la multiplicas por 100. El problema es que al multiplicarla por 100 no necesariamente te va a quedar entera ya que floatval no es una función que puedas controlar la cantidad de decimales que retorne. Un ejemplo es que asumamos el $val['precio'] como 150.4872 al multiplicarlo por 100 nos queda como 15048.72 que aún sigue siendo un decimal. Mi consejo es que redondees el número a dos decimales antes de multiplicarlo por 100. Algo así
```php
$precio = round(floatval($val['precio']), 2);
$precio = $precio*100;
```

**Comment by Oscar10056** [comment]
Ok, lo reviso
