### ISSUE TITLE
subscription.paid en Webhooks

### ISSUE THREAD

**Issue by mariomeraz** [conekta/conekta-php#184]
Hola!,

Tienen la estructura Json del evento **subscription.paid** ?

Ya que quiero que cuando se realice este evento se mande el correo de notificacion.

Saludos

**Comment by apodacaduron** [comment]
Hola que tal, la puedes imprimir tu mismo al recibir el post en tu controlador pero te paso una de todas maneras
```php
[2020-11-07 11:13:16] local.DEBUG: array (
  'data' => 
  array (
    'object' => 
    array (
      'id' => 'sub_xxxxxxx',
      'status' => 'active',
      'object' => 'subscription',
      'charge_id' => 'xxxxx',
      'created_at' => 1604772782,
      'subscription_start' => 1604772782,
      'canceled_at' => NULL,
      'paused_at' => NULL,
      'billing_cycle_start' => 1604772772,
      'billing_cycle_end' => 1612721572,
      'trial_start' => NULL,
      'trial_end' => NULL,
      'plan_id' => 'basic',
      'last_billing_cycle_order_id' => 'ord_xxxxx',
      'customer_id' => 'cus_xxxxxx',
      'customer_custom_reference' => NULL,
      'card_id' => 'src_xxxxxxx',
    ),
    'previous_attributes' => 
    array (
    ),
  ),
  'livemode' => false,
  'webhook_status' => 'pending',
  'webhook_logs' => 
  array (
    0 => 
    array (
      'id' => 'webhl_xxxxxxxx',
      'url' => 'http://xxxx.ngrok.io/api/conekta-webhook',
      'failed_attempts' => 0,
      'last_http_response_status' => -1,
      'response_data' => NULL,
      'object' => 'webhook_log',
      'last_attempted_at' => 0,
    ),
  ),
  'id' => 'xxx',
  'object' => 'event',
  'type' => 'subscription.paid',
  'created_at' => 1604772784,
)
```

**Comment by jesusgomezhdez** [comment]
@apodacaduron  ¿Hay alguna manera de poder validar que quién hace esta acción es conekta y no otro sitio? ¿Puedo detectar en mi controlador, cuando se activa el webhook, sus ips para saber que en efecto la petición al endpoint proviene de los servidores de conekta?

**Comment by apodacaduron** [comment]
@jesusgomezhdez tal vez deberías abrir otro issue para consultar este detalle en especifico, pero al menos en la documentación de Conekta no e visto que venga ningún tema de seguridad para Webhooks pero por ejemplo en stripe te muestra algunos tipos de validación que hay y te da a conocer que si lo puedes hacer por ip pero hay muchas diferentes, o por el origen del request, la verdad no e probado nada de esto, pero espero encuentres una respuesta

[Stripe Webhook Security](https://stripe.com/docs/webhooks/best-practices#security)
[Obtener Origen de request con php](https://stackoverflow.com/questions/41326257/how-i-can-get-origin-of-request-with-php/41335048)

**Comment by kpadilla2020** [comment]
@apodacaduron como puedo acceder a la propiedad customer_id?
