### ISSUE TITLE
Obtener order_id con webhook al realizarse pago

### ISSUE THREAD

**Issue by israelwong** [conekta/conekta-php#187]
Hola a devs, espero me puedan apoyar, llevo rato intentando y no puedo.

Necesito obtener el "order_id" de una transacción cuando ha sido pagada, solo puedo obtener el ID. y este último no me sirve.

$body = @file_get_contents('php://input');
$data = json_decode($body);
http_response_code(200); // Return 200 OK
echo $data->id; // me entrega el ID y yo quiero el order_id

Muchas gracias por su apoyo

**Comment by fcarrero** [comment]
cuando recibes un evento de order.paid
dentro del json que recibes viene un objeto llamado data, allí puedes encontrar el id de la order
