### ISSUE TITLE
Formato inválido para name al crear Customer

### ISSUE THREAD

**Issue by apercova** [conekta/conekta-php#189]
Que tal.

Tengo el error `conekta.errors.parameter_validation.name.invalid` al intentar crear un Customer con la version `v2.0.0` del API de Conekta.

Creo que el problema es por codificación de caracteres, sin embargo, revisando en la documentación del API : https://developers.conekta.com/reference, no encuentro referencia a algún set de caracteres o encoding específico.

El nombre del Customer que se intenta crear debo tenerlo tal cual es, sin embargo el API no me deja crearlo.

¿Su API soporta Unicode?, de no ser así, ¿podrían indicarme qué caracteres son válidos para el nombre de un Customer o cómo dar de alta Customers con las características de los casos que adjunto?

Adjunto estos dos casos el los que la validación del nombre no pasa:

1. El nombre contiene un acento grave [U+0060](https://unicode-table.com/es/0060/) el cuál es un caracter ASCII válido,
```
curl --location --request POST 'https://api.conekta.io/customers' \
--header 'Accept: application/vnd.conekta-v2.0.0+json' \
--header 'Authorization: Basic enJTV...' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "someone@company.com",
    "name": "Luis Johnson`s",
    "payment_sources": [
        {
            "type": "oxxo_recurrent"
        }
    ]
}'
```

2. El nombre contiene caracteres unicode en griego.
He revisado este issue relacionado: https://github.com/conekta/conekta-php/issues/166 [Formato inválido para name al crear cargo](https://github.com/conekta/conekta-php/issues/166) y veo que al parecer su API no soporta números en el nombre del Customer, por lo que el codepoint de unicode `\u0391\u0396\u0391\u039d\u0399` no funciona.
Sin embargo, también he probado enviar el texto `ΑΖΑΝΙ` tal cual, sin embargo el error es el mismo.

```json
curl --location --request POST 'https://api.conekta.io/customers' \
--header 'Accept: application/vnd.conekta-v2.0.0+json' \
--header 'Authorization: Basic enJTV...' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "someone@company.com",
    "name": "Calos ΑΖΑΝΙ",
    "payment_sources": [
        {
            "type": "oxxo_recurrent"
        }
    ]
}'
```

El error que me devuelve el API es el siguiente:
```json
{
    "details": [
        {
            "debug_message": "Invalid format for \"name\".",
            "message": "Formato inválido para \"name\".",
            "param": "name",
            "code": "conekta.errors.parameter_validation.name.invalid"
        }
    ],
    "object": "error",
    "type": "parameter_validation_error",
    "log_id": "5fe411986a77454fbda9aaa6"
}
```

Espero me puedan apoyar con este issue. 
Saludos.

**Comment by victorct-pronto** [comment]
Tenemos el mismo problema usando números, pero con la librería de Python :/

**Comment by fcarrero** [comment]
buenas, estas ya son validaciones internas a nivel de Api
