### ISSUE TITLE
Mensaje de error

### ISSUE THREAD

**Issue by kpadilla2020** [conekta/conekta-php#193]
Como puedo obtener el mensaje de error por el cual la suscripción no se pudo realizar. Por ejemplo cuando paga con tarjeta y hay algun error me manda un mensaje "Esta tarjeta no tiene fondos suficientes" o algo así, pero con las suscripciones no pasa lo mismo, entonces ¿como puedo obtener el mensaje de error? con esta función creo la suscripción.

    public function suscripcion($obj) {
        $var;
        try {
            \Conekta\Conekta::setApiKey($this->key);
            $customer = \Conekta\Customer::create([
                "name" => $obj['nombre'],
                "email" => $obj['correo'],
                "phone" => $obj['telefono'],
                "payment_sources" => [
                    [
                        "type" => "card",
                        "token_id" => $obj['token']
                    ]
                ],
            ]);
            $subscription = $customer->createSubscription([
                'plan' => $obj['plan-conekta']
            ]);
            return $subscription;
        }
        catch (\Conekta\ProcessingError $error) {
            $var = 'Suscripcion: '.$error->getMessage();
        }
        catch (\Conekta\ParameterValidationError $error) {
            $var = 'Suscripcion: '.$error->getMessage();
        }
        catch (\Conekta\Handler $error) {
            $var = 'Suscripcion: '.$error->getMessage();
        }
        return $var;
    }

**Comment by fcarrero** [comment]
el sdk se ha actualizado, recomendamos actualizar a las ultimas versiones
