### ISSUE TITLE
Crear token vacío con libreria php

### ISSUE THREAD

**Issue by izzy-dreisen** [conekta/conekta-php#199]
saludos, Como obtengo token vacio con la api en php 
se que necesito enviar la peticion:
`curl --location --request POST 'https://api.conekta.io/tokens' \
--header 'Accept: application/vnd.conekta-v2.0.0+json' \
--header 'Accept-Language: es' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic S2V5X0xsYXZlUFJJVkFEQTEyMzQ1Njc4OQ==' \
--data-raw '{
    "checkout": {
    "returns_control_on": "Token"
    }
}'`
y veo que puedo obtener de alguna forma con la libreria en php pero no se como invocar esas funciones
` $token = Token::create(self::$validTokenWithCheckout);`
como podria obtener el token de manera correcta y transparente usando la libreria php para despues usarlo en en paso 2 ddel tutorial https://developers.conekta.com/page/cargo-por-solicitud-web-checkout-tokenizer

**Comment by fcarrero** [comment]
ya lo puedes hacer
https://github.com/conekta/conekta-php/blob/5720aef36991dfa74041c3fbd77ee12e6e46329c/lib/Api/TokensApi.php#L139
