### ISSUE TITLE
pagos Oxxo, attribute first_paid_at is missing, account_created_at is missing

### ISSUE THREAD

**Issue by DSotoOficial** [conekta/conekta-php#203]
Al hacer una llamada para crear una orden de pago oxxo_cash, obtengo error por la falta de los atributos first_paid_at, account_created_at y paid_transactions, algo que contradice la documentación o tal vez algo no estoy entendiendo bien del porque de esos campos y de donde obtener su valor para ponerlo, porgo el ejemplo de los datos json y su respuesta por si alguien sabe:

Petición json:
```
{
	"line_items": [
		{
			"name": "Boleto de prueba",
			"unit_price": 16127,
			"quantity": 1,
			"antifraud_info": {
				"trip_id": "01",
				"departs_at": 1654732989,
				"arrives_at": 1654819389,
				"ticket_class": "Ordinario",
				"seat_number": "01",
				"passenger_type": "Adulto",
				"origin": "Tijuana",
				"destination": "Los Mochis",
				"paid_transactions": 1
			}
		}
	],
	"currency": "MXN",
	"customer_info": {
		"name": "Juan Manuel Ramirez",
		"email": "juanmanual999@gmail.com",
		"phone": "+525555555555"
	},
	"charges": [
		{
			"payment_method": {
				"type": "oxxo_cash",
				"expires_at": 1654653789
			}
		}
	]
}

```

Respuesta:

{
	"details": [
		{
			"debug_message": "The \"customer_info attribute antifraud_info attribute paid_transactions\" is missing.",
			"message": "El parametro paid_transactions\" es requerido.",
			"param": "customer_info.antifraud_info.paid_transactions",
			"code": "conekta.errors.parameter_validation.customer_info.antifraud_info.paid_transactions.missing"
		},
		{
			"debug_message": "The \"customer_info attribute antifraud_info attribute account_created_at\" is missing.",
			"message": "El parametro account_created_at\" es requerido.",
			"param": "customer_info.antifraud_info.account_created_at",
			"code": "conekta.errors.parameter_validation.customer_info.antifraud_info.account_created_at.missing"
		},
		{
			"debug_message": "The \"customer_info attribute antifraud_info attribute first_paid_at\" is missing.",
			"message": "El parametro first_paid_at\" es requerido.",
			"param": "customer_info.antifraud_info.first_paid_at",
			"code": "conekta.errors.parameter_validation.customer_info.antifraud_info.first_paid_at.missing"
		}
	],
	"object": "error",
	"type": "parameter_validation_error",
	"log_id": "629fe73d0211a6514381eb0b"
}

**Comment by fcarrero** [comment]
que version de la api estas usando ?
