### ISSUE TITLE
PHP 8.2: Dynamic Properties are deprecated

### ISSUE THREAD

**Issue by amadohin** [conekta/conekta-php#209]
Se recibe error dynamic Properties are deprecated en las siguientes clases:

conekta-php/lib/

	Requestor.php
	ConektaObject.php
	ConektaList.php
	Order.php

Para solventar temporalmente agregar:

**_#[\AllowDynamicProperties]_**

```
<?php

namespace Conekta;

use Conekta\{Conekta, ConektaResource, Exceptions, Requestor, Util};

**_#[\AllowDynamicProperties]_**
class ConektaList extends ConektaObject
{
    public const LIMIT = 5;

    public function __construct($elements_type, $params = [])
    {
        parent::__construct();
        $this->elements_type = $elements_type;
        $this->params = $params;
        $this->total = 0;
    }
```

Mas info:
	https://php.watch/versions/8.2/dynamic-properties-deprecated

**Comment by fcarrero** [comment]
@amadohin gracias por la info, lo vamos a estar patch en los proxímos días
