### ISSUE TITLE
El cliente 'cus_id' no tiene una tarjeta válida con API 2.0

### ISSUE THREAD

**Issue by juanmendez92** [conekta/conekta-php#67]
Usando Laravel tengo este código:

```
            try {
                $customer = Customer::create([
                    "name" => $user->complete_name,
                    "email" => $user->email,
                    "cards" => [
                        $request->conektaTokenId
                    ]
                ]);

                $subscription = $customer->createSubscription([
                    "plan" => $request->period
                ]);

                return response()->json([
                    'message' => 'Suscripción creada.',
                ], 200);
            } catch (Error $e) {
                return response()->json([
                    'message' => $e
                ], 422);
            }

```

Pero me devuelve una excepción con estos datos:

- in ErrorList.php line 20
- at ErrorList::errorHandler(array('details' => array(array('debug_message' => 'The customer cus_2fxcXN6F7GR91QJFy does not have a valid card.', 'message' => 'El cliente cus_2fxcXN6F7GR91QJFy no tiene una tarjeta válida.', 'code' => 'processing_error')), 'object' => 'error', 'type' => 'processing_error'), 402) in Requestor.php line 100
- at Requestor->request('post', 'https://api.conekta.io/customers/cus_2fxcXN6F7GR91QJFy/subscription', array('plan' => 'standard_trimestral')) in Resource.php line 151
- at Resource->_createMember('subscription', array('plan' => 'standard_trimestral')) in Customer.php line 131

**Comment by MauricioMurga** [comment]
Hola @juanmendez92, me puedes pasar un id de un cargo, customer o tarjeta para revisar tus logs y ver lo que está pasando?

**Comment by juanmendez92** [comment]
Claro, el id de customer que se generó la última vez fue cus_2fya56Yw2hx129eSv con token tok_2fya555HzJpgrEkq9 y este su último log generado al tratar de crear una suscripción:
{
	"details": [
		{
			"debug_message": "The customer cus_2fya56Yw2hx129eSv does not have a valid card.",
			"message": "El cliente cus_2fya56Yw2hx129eSv no tiene una tarjeta válida.",
			"code": "processing_error"
		}
	],
	"object": "error",
	"type": "processing_error"
}

**Comment by MauricioMurga** [comment]
Hola @juanmendez92, en el API 2.0.0 se hicieron algunos cambios en los parámetros. Para crear un customer con tarjetas en una sola llamada se tiene que agregar lo siguiente:

``'payment_sources' => array(array(
                'token_id' => 'tok_test_visa_4242',
                'type' => 'card'
            ))``
tal como viene en https://github.com/conekta/conekta-php/blob/2b5d3ed1012ace23f96db7cc4e6d3ddb52cafa8b/test/Conekta-2.0/SourceTest.php#L8

Una disculpa, lanzaremos la nueva documentación el lunes.
