### ISSUE TITLE
[Conekta][Customer] | - payment_sources tiene un tipo inválido.

### ISSUE THREAD

**Issue by nietzcheson** [conekta/conekta-php#79]
Hi! I was trying to create a client, following the reference [documentation](https://developers.conekta.com/api?language=php#create-customer). 
I got the following error:
````
payment_sources tiene un tipo inválido.
````
```php
$customer = \Conekta\Customer::create(
  array(
    'name'  => "Mario Perez",
    'email' => "usuario@example.com",
    'phone' => "+5215555555555",
    'plan_id'  => "gold-plan",
    'corporate' => true,
    'payment_sources' => array(
        'token_id' => "tok_test_visa_4242",
        'type' => "card"
    ),
    'shipping_contacts' => array(array(
      'phone' => "+5215555555555",
      'receiver' => "Marvin Fuller",
      'between_streets' => "Ackerman Crescent",
      'address' => array(
        'street1' => "250 Alexis St",
        'street2' => "fake street",
        'city' => "Red Deer",
        'state' => "Alberta",
        'country' => "CA",
        'postal_code' => "T4N 0B8",
        'residential' => true
      )
    ))
  )
);
````
It is a recurring error: #67  

Please modify the documentation ... thanks ...

**Comment by KarlaRobinson** [comment]
Thank you for notifying us!

The corrected example would be:

bc.
$customer = \Conekta\Customer::create(
  array(
    'name'  => "Mario Perez",
    'email' => "usuario@example.com",
    'phone' => "+5215555555555",
    'plan_id'  => "gold-plan",
    'corporate' => true,
    'payment_sources' => array(
    	array(
        'token_id' => "tok_test_visa_4242",
        'type' => "card"
    )),
    'shipping_contacts' => array(array(
      'phone' => "+5215555555555",
      'receiver' => "Marvin Fuller",
      'between_streets' => "Ackerman Crescent",
      'address' => array(
        'street1' => "250 Alexis St",
        'street2' => "fake street",
        'city' => "Red Deer",
        'state' => "Alberta",
        'country' => "CA",
        'postal_code' => "T4N 0B8",
        'residential' => true
      )
    ))
  )
);

**Comment by KarlaRobinson** [comment]
Thank you for notifying us!

The corrected example would be:

`$customer = \Conekta\Customer::create(
  array(
    'name'  => "Mario Perez",
    'email' => "usuario@example.com",
    'phone' => "+5215555555555",
    'plan_id'  => "gold-plan",
    'corporate' => true,
    'payment_sources' => array(
    	array(
        'token_id' => "tok_test_visa_4242",
        'type' => "card"
    )),
    'shipping_contacts' => array(array(
      'phone' => "+5215555555555",
      'receiver' => "Marvin Fuller",
      'between_streets' => "Ackerman Crescent",
      'address' => array(
        'street1' => "250 Alexis St",
        'street2' => "fake street",
        'city' => "Red Deer",
        'state' => "Alberta",
        'country' => "CA",
        'postal_code' => "T4N 0B8",
        'residential' => true
      )
    ))
  )
);`

**Comment by KarlaRobinson** [comment]
Thank you for notifying us!

The corrected example would be:

> $customer = \Conekta\Customer::create(
  array(
    'name'  => "Mario Perez",
    'email' => "usuario@example.com",
    'phone' => "+5215555555555",
    'plan_id'  => "gold-plan",
    'corporate' => true,
    'payment_sources' => array(
    	array(
        'token_id' => "tok_test_visa_4242",
        'type' => "card"
    )),
    'shipping_contacts' => array(array(
      'phone' => "+5215555555555",
      'receiver' => "Marvin Fuller",
      'between_streets' => "Ackerman Crescent",
      'address' => array(
        'street1' => "250 Alexis St",
        'street2' => "fake street",
        'city' => "Red Deer",
        'state' => "Alberta",
        'country' => "CA",
        'postal_code' => "T4N 0B8",
        'residential' => true
      )
    ))
  )
);

**Comment by KarlaRobinson** [comment]
Thank you for notifying us!

Below is the corrected example:

```php
$customer = \Conekta\Customer::create(
  array(
    'name'  => "Mario Perez",
    'email' => "usuario@example.com",
    'phone' => "+5215555555555",
    'plan_id'  => "gold-plan",
    'corporate' => true,
    'payment_sources' => array(
    	array(
        'token_id' => "tok_test_visa_4242",
        'type' => "card"
    )),
    'shipping_contacts' => array(array(
      'phone' => "+5215555555555",
      'receiver' => "Marvin Fuller",
      'between_streets' => "Ackerman Crescent",
      'address' => array(
        'street1' => "250 Alexis St",
        'street2' => "fake street",
        'city' => "Red Deer",
        'state' => "Alberta",
        'country' => "CA",
        'postal_code' => "T4N 0B8",
        'residential' => true
      )
    ))
  )
);
````

**Comment by DanielApodaca** [comment]
Este problema aún se encuentra presente en la documentación al día de hoy 01-11-12
[Link](https://developers.conekta.com/reference/clientes)
`'payment_sources' => [
        'token_id' => "tok_test_visa_4242",
        'type' => "card"
    ],`
