### ISSUE TITLE
Error try to make instance of PaymentSource class after create payment source.

### ISSUE THREAD

**Issue by mrljaime** [conekta/conekta-php#81]
The error cames on **Conekta/Resource.php** on line 181 when I'm trying to create a payment source. 

The log in admin Conekta says that post request was successfully, the try/catch block doesn't catch the error:

**"Attempted to load class \"Payment_sources\" from namespace \"\\Conekta\"**

**"$class = '\\Conekta\\' . ucfirst($member);"**

Thanks.

**Comment by eduardoconekta** [comment]
Puedes poner el snipet de tu codigo aqui ?, a simple vista con el debug solo me indica que posiblemente no se concateno un nombre de clase correcto como dice en la primera linea Payment_sources, deberia ser PaymentSource pero necesito un poco mas de contexto de tu app por favor

**Comment by mrljaime** [comment]
Lo que está ocurriendo es que cuando trato de crear un nuevo método de pago 
**$source = $customer->createPaymentSource($updatePaymentResources);**

El retorno de ese método genera una instancia de PaymentSource, sin embargo, el código toma una variable que se llama "$member"

Aquí está el stackTrace:


**request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Payment_sources" from namespace "\Conekta". Did you forget a "use" statement for another namespace?" at /Users/josejaime/Workspace/api/vendor/conekta/conekta-php/lib/Conekta/Resource.php line 181 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Payment_sources\" from namespace \"\\Conekta\".\nDid you forget a \"use\" statement for another namespace? at /Users/josejaime/Workspace/api/vendor/conekta/conekta-php/lib/Conekta/Resource.php:181)"} []**

Quedo atento.

**Comment by eduardoconekta** [comment]
$member es un parametro que toma la función `_createMember` dentro de Resource.php esta variable no tiene contacto desde el inicio del stack, únicamente pasas los parametros:
```
$customer->createPaymentSource($PARAMETROS);
```
la variable member se usa en el siguiente paso en la funcion `createPaymentSource` dentro de esta se pasan estos 3 valores 
```
(  'payment_sources', $PARAMETROS, $this(objeto clase) )
```

que ya en _createMember => $member es igual al string 'payment_sources'.

podrias crear un gist con todo tu codigo principal solo el php donde tienes el problema, ya que el error efectivamente recae en la linea <a href="https://github.com/conekta/conekta-php/blob/master/lib/Conekta/Resource.php#L181">181 de resource</a> para que pueda ver como estan construidas tus peticiones, Gracias !

**Comment by mrljaime** [comment]
https://gist.github.com/mrljaime/363c735a2f06f910388ceec20c1134af

En el comentario de la linea 3 está la construcción de lo que al final termina siendo mi variable:
`$updatePaymentResources`

`$updatePaymentResources = ["token_id" => "token", "type" => "card"]`

Los cuáles, son los parámetros que la documentación propone para crear un nuevo recurso. 
En la llamada a _createMember que tu mencionas, donde $member es igual al string "payment_sources" está dentro del SDK, por mi parte, jamás envío un "algo" con esa llave. 
El problema es que el SDK no tiene declarada una clase de tipo *Payment_sources*, pues es lo que está realizando, siguiendo el ejemplo y asumiendo que sé algo al respecto, intenta hacer algo como esto:

`$class = '\\Conekta\\' . ucfirst($member);`

Donde $member puede ser: 

order, customer, card, payment_source. 

¿Existe alguna clase dentro del SDK que se llame **Payment_sources**?
¿Realmente el nombre de la clase no es **PaymentSource**? Estamos de acuerdo que si la clase no existe, jamás podrá ser instanciada.

**Comment by eduardoconekta** [comment]
Ok, Mira lo que puedes hacer es mandar a llamar de nuevo el `Customer::find` ya que tenemos un bug en la api por que remotamente si se borra el payment_source pero localmente no, entonces después de un delete hay una descompensación entre lo que tiene la api y lo que tiene el objeto local, trabajaremos en ese error para corregirlo, Muchas gracias
_Nota:_ PaymentSource es la clase en php y payment_source es el endpoint de la api, hacia donde llegan las peticiones.

**Comment by mrljaime** [comment]
Sólo te hago mención que lo que está ocurriendo es que, justamente, la llave con la que se hace la llamada a _createMember, en la cual se genera la llamada al endpoint **payment_source**, está intentando generar una clase con esa misma cadena, que justamente es donde no encuentra la clase de Php, ya que no se llama **Payment_source** sino **PaymentSource**. Entiendo que intentaron reciclar esa llave, sólo que no consideraron el nombre de la clase cuando lo desarrollaron y sigue causando un error en la linea 181 de Resource.php. 

Sugeriría que la variable $member sea la llave de una constante de tipo arreglo, donde la llave es el endpoint, y el valor la clase. 
```
const ARRAY = [
    "payment_source" => "PaymentSource", 
    "order"                   => "Order", 
];
```

**Comment by eduardoconekta** [comment]
Si, ya veo lo que me explicas, en el siguiente release se arreglara esa parte que es por la clase y no por una descompensación , Gracias de nuevo Jaime!

**Comment by eduardoconekta** [comment]
Cuando quieras comenzar a utilizar la librería puedes bajar el branch *Feature/refactoring* o esperar el release que esta en el ultimo request para que los cambios sean aceptados.
_nota: _ En los siguientes días se estará liberando esta version.
