### ISSUE TITLE
API Phone-Number Error Validation Message

### ISSUE THREAD

**Issue by Adrian0350** [conekta/conekta-php#83]
API Phone Number validation message throws an ambiguous text in spanish: "Número inválido" (or something like that) when the phone number has an incorrect format or is invalid.

The problem that I've encountered with this issue (and with different projects) in particular is that  it's hard to deduce what number Conekta is talking about.

Perhaps something that says "Número de teléfono inválido" would be much appreciated.

Not a critical upgrade though…

**Comment by KarlaRobinson** [comment]
That's a good point @Adrian0350 - thanks for writing to us, we will definitely consider this change.

**Comment by Adrian0350** [comment]
Thanks a bunch @KarlaRobinson!
