### ISSUE TITLE
Error Undefined offset: 0

### ISSUE THREAD

**Issue by gabohm** [conekta/conekta-php#85]
Hola, estoy tratando de crear un Customer y se mi regresa el customer ID pero me marca un error: 
ErrorException in VarCloner.php line 74:
Undefined offset: 0

Estoy trabajando con Laravel 5

Aquí esta el código:
try {
			  	$customer = \Conekta\Customer::create(
				    array(
				      "name" => "Gabriel Herrera",
				      "email" => "gabohm@live.com.mx",
				      "phone" => "5556879595",
				      "payment_sources" => array(
				        array(
				            "type" => "card",
				            "token_id" => "tok_test_visa_4242"
				        )
				      )//payment_sources
				    )//customer
				  );
			  	echo $customer->id;
			} catch (\Conekta\ErrorList $errorList){
			  	foreach($errorList->details as &$errorDetail) {
			    	echo $errorDetail->getMessage() . "\r\n";
			  	}
			}

Adjunto captura de pantalla:
<img width="1153" alt="captura de pantalla 2017-05-18 a la s 17 05 12" src="https://cloud.githubusercontent.com/assets/10179814/26225856/e15b31e2-3bee-11e7-8094-767c61fb15b5.png">

Saludos.

**Comment by eduardoconekta** [comment]
Hola @gabohm, valide tu sintaxis y esta todo bien, el caso es que algo en el código quiere acceder a un indice que no existe, puedes hacer un gist con tu función o flujo para que pueda tener un poco mas de contexto ?

**Comment by danieluyo** [comment]
@gabohm no es problema de conekta por que  el customer se generó correctamente:
> cus_2XXXXX

**Comment by eduardoconekta** [comment]
Este issue se cierra por que el motivo es externo a la libreria de conekta
