### ISSUE TITLE
The token has already been used

### ISSUE THREAD

**Issue by RodrigoRMG** [conekta/conekta-php#89]
Al intentar generar una orden de prueba no acepta la tarjeta y dice "The token has already been used" 

 [0]=>
    object(stdClass)#172 (3) {
      ["debug_message"]=>
      string(32) "The token has already been used."
      ["message"]=>
      string(33) "La tarjeta no pudo ser procesada."
      ["code"]=>
      string(43) "conekta.errors.processing.tokenization.used"
    }
  }

**Comment by eduardoconekta** [comment]
Tal vez en el flujo de código hay algún bug que recicle el ultimo token generado, depende de la implementación, ej. frameworks que cacheen variables, si es un error recurrente déjanos un gist con el flujo de tu código y con gusto te ayudamos @RodrigoRMG 👍

**Comment by eduardoconekta** [comment]
I close this issue for lack of information and issuer disregard
