### ISSUE TITLE
Double payment on subscription!

### ISSUE THREAD

**Issue by victorhqc** [conekta/conekta-php#9]
Hi, I'm trying to implement a subscription system using conekta and there is an odd behaviour in the payments and I don't know if there's something going wrong.

## Creating the plan
Code:
![plan_code](https://cloud.githubusercontent.com/assets/726113/6947323/3afaab64-d85b-11e4-80f5-7c92a72de66b.png)

And is correctly created (except for the 6 months instead of 12 but I don't think that's a problem)
![plan](https://cloud.githubusercontent.com/assets/726113/6947334/5491ed58-d85b-11e4-8420-c4cf4d587701.png)

## Creating the client
After the plan is created I make a new test client.
![client_code](https://cloud.githubusercontent.com/assets/726113/6947359/76932728-d85b-11e4-983c-8e38b334dc55.png)

Correctly created:
![client](https://cloud.githubusercontent.com/assets/726113/6947366/7f0b8152-d85b-11e4-8d37-841ba72a328c.png)

## Subscribing
Here is the problem, I make just one request to subscribe and get all the information from the API correct, but it generates 2 payments instead of 1:
![subscribe_code](https://cloud.githubusercontent.com/assets/726113/6947376/9b740aa8-d85b-11e4-9e53-43659891cae9.png)

![subscribe](https://cloud.githubusercontent.com/assets/726113/6947377/a25e0eb8-d85b-11e4-9d7f-837b1c8a5b10.png)

I'm I doing something wrong? Or is this how is supposed to work? Its weird cause is always 2 minutes difference between the 2 charges.

Thanks in advance!

**Comment by leofischer** [comment]
Hi @victorhqc,

This looks to be an issue from our end, we are revamping the subscription code base and there was an temporary bug.  If you try again this should work fine, for the meantime I am closing this issue.
Best,

-Leo

**Comment by victorhqc** [comment]
Oh nice, thanks for answering! :)
